apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sysdig-agent
  namespace: sysdig-agent
spec:
  selector:
    matchLabels:
      name: sysdig-agent
  template:
    metadata:
      labels:
        name: sysdig-agent
    spec:
      containers:
      - name: sysdig-agent
        image: sysdig/agent
        securityContext:
          privileged: true
        env:
          - name: ACCESS_KEY
            value: "783baa11-9875-48ad-8a4d-969ec1d72630"
          - name: TAGS
            value: "k8s_cluster: kind-kind"
