apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      evaluation_interval: 15s
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets:
            - 'localhost:9090'

      - job_name: 'kube-state-metrics'
        static_configs:
          - targets:
            - 'kube-state-metrics:8181'

      - job_name: 'nginx'
        static_configs:
          - targets:
            - 'localhost:8080'

