name: Deploy Nginx on Kind Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Kind
        run: |
          curl -Lo kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
          chmod +x kind
          sudo mv kind /usr/local/bin/
        shell: bash

      - name: Create Kind Cluster
        run: kind create cluster --config kind-config.yaml
        # Replace "kind-config.yaml" with your Kind configuration file's name.

      - name: Set Kubeconfig
        run: echo "$KUBECONFIG" > $HOME/.kube/config

      - name: Deploy Nginx
        run: |
          kubectl create deployment nginx-deployment --image=nginx
          kubectl expose deployment nginx-deployment --port=80 --type=LoadBalancer
        # This deploys Nginx and exposes it on port 80 using a LoadBalancer service.

      - name: Wait for Nginx to Start
        run: kubectl wait --for=condition=available deployment/nginx-deployment

      - name: Get Nginx Service URL
        run: |
          echo "Nginx is now running at: http://$(kubectl get svc nginx-deployment -o jsonpath='{.status.loadBalancer.ingress[0].ip}')"
        # This retrieves the IP address of the LoadBalancer service to access Nginx.

