name: Create Self-Hosted K8s Cluster

on:
  push:
    branches:
      - main

jobs:
  create-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Create K8s cluster
        run: |
          kind create cluster --name my-k8s-cluster

      - name: Configure kubectl
        run: |
          kubectl cluster-info --context kind-my-k8s-cluster

      - name: Print Cluster Info
        run: |
          kubectl cluster-info
      
      - name: run the nginx file
        run: |
          kubectl apply -f ./nginx-deployment.yaml
          kubectl get deployments

      - name: Install Sysdig Monitor Agent
        run: |
          curl -s https://agent.sysdig.com/install | bash -s -- -a $SYSDIG_ACCESS_KEY

      - name: Install Sysdig Secure Agent
        run: |
          curl -s https://secure.sysdig.com/install | bash -s -- -a $SYSDIG_ACCESS_KEY

      - name: Port Forward to NGINX
        run: |
          kubectl port-forward deployment/nginx-deployment 8080:80 &

      - name: Wait for NGINX to start
        run: sleep 10

      - name: Access NGINX
        run: curl http://localhost:8080
