name: Create Self-Hosted K8s Cluster

on:
  push:
    branches:
      - main

jobs:
  create-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Create K8s cluster
        run: |
          kind create cluster --name my-k8s-cluster

      - name: Configure kubectl
        run: |
          export KUBECONFIG="$(kind get kubeconfig-path --name="my-k8s-cluster")"

      - name: Print Cluster Info
        run: |
          kubectl cluster-info
