name: Deploy NGINX to KIND

on:
  push:
    branches:
      - basic

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up KIND
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
        chmod +x ./kind
        mv ./kind /usr/local/bin/
        kind create cluster --name my-cluster
        kind get clusters
        ls ~/.kube+


    - name: Deploy NGINX
      run: |
        kubectl apply -f ./nginx-deployment.yaml
        kubectl apply -f ./nginx-service.yaml
        kubectl get svc nginx-service


    - name: Wait for NGINX pods to be ready
      run: kubectl wait --for=condition=ready pod -l app=nginx --timeout=300s

    - name: Access NGINX
      run: |
        NGINX_PORT=$(kubectl get svc/nginx-service -o=jsonpath='{.spec.ports[0].nodePort}')
        NODE_IP=$(kubectl get nodes -o=jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')
        NGINX_URL="http://${NODE_IP}:${NGINX_PORT}/"
        echo "NGINX URL: $NGINX_URL"


    - name: integrate sysdig-agent
      run: |
        curl -s https://download.sysdig.com/stable/install-agent | sudo bash -s -- --access_key 2228ea51-ce66-4e26-902a-da1ef8a2c209 --collector ingest.us4.sysdig.com --secure true
      # sudo systemctl status sysdig-agent
      # sudo systemctl enable sysdig-agent
      # sudo systemctl start sysdig-agent

      #         helm install -n sysdig-agent sysdig sysdig/sysdig-deploy -f ./values.sysdig.yaml
      # ./kind-deploy-app-helloweb.sh



