name: Deploy NGINX to KIND

on:
  push:
    branches:
      - basic

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up KIND
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
        chmod +x ./kind
        mv ./kind /usr/local/bin/
        kind create cluster --config=kind-config.yaml
      working-directory: .github/workflows

    - name: Deploy NGINX
      run: |
        kubectl apply -f nginx-deployment.yaml


    - name: integrate sysdig-agent
      run: |
        curl -s https://download.sysdig.com/stable/install-agent | sudo bash -s -- --access_key 2228ea51-ce66-4e26-902a-da1ef8a2c209 --collector ingest.us4.sysdig.com --secure true
      # sudo systemctl status sysdig-agent
      # sudo systemctl enable sysdig-agent
      # sudo systemctl start sysdig-agent

      #         helm install -n sysdig-agent sysdig sysdig/sysdig-deploy -f ./values.sysdig.yaml
      # ./kind-deploy-app-helloweb.sh



