name: Deploy kube-state-metrics in KinD

on:
  push:
    branches:
      - kubestatemetrics  # Change to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install KinD
        run: |
          curl -Lo kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
          chmod +x kind
          sudo mv kind /usr/local/bin/

      - name: Create KinD Cluster
        run: kind create cluster

      - name: Deploy kube-state-metrics
        run: |
          kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

      - name: Checking the kube-state-metrics
        run: |
          kubectl get pods --all-namespaces
          kubectl get nodes --all-namespaces
          kubectl top pods --all-namespaces -l tier=control-plane --sort-by=cpu

      - name: prometheus
        run: |
          wget https://github.com/prometheus/prometheus/releases/download/v2.30.3/prometheus-2.30.3.linux-amd64.tar.gz
          tar xvfz prometheus-2.30.3.linux-amd64.tar.gz
          cd prometheus-2.30.3.linux-amd64
