name: Deploy kube-state-metrics in KinD

on:
  push:
    branches:
      - kubestatemetrics  # Change to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install KinD
        run: |
          curl -Lo kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
          chmod +x kind
          sudo mv kind /usr/local/bin/

      - name: Create KinD Cluster
        run: kind create cluster

      - name: Deploy kube-state-metrics
        run: |
          kubectl apply -f https://github.com/kubernetes/kube-state-metrics/releases/download/v2.1.0/kubernetes/kube-state-metrics-deployment.yaml
