name: continuous-integration

on:
  push:
    branches:
    - kubestatemetrics


jobs:
  test-e2e:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s-version: ['v1.24.2']
        kubectl-version: ['v1.25.0']
        kind-version: ['v0.14.0']

    steps:
    - uses: actions/checkout@v3

    - name: kubectl version
      run: kubectl

    - name: get deployment status
      run: |
        kubectl apply -f kube-state-metrics-config/
        kubectl get deployments kube-state-metrics -n kube-system